const commerce = require('./commerce.config.json')

module.exports = {
  commerce,
  env: {
    BIGCOMMERCE_STOREFRONT_API_URL: process.env.BIGCOMMERCE_STOREFRONT_API_URL,
    BIGCOMMERCE_STOREFRONT_API_TOKEN: process.env.BIGCOMMERCE_STOREFRONT_API_TOKEN,
    BIGCOMMERCE_STORE_API_URL: process.env.BIGCOMMERCE_STORE_API_URL,
    BIGCOMMERCE_STORE_API_TOKEN: process.env.BIGCOMMERCE_STORE_API_TOKEN,
    BIGCOMMERCE_STORE_API_CLIENT_ID: process.env.BIGCOMMERCE_STORE_API_CLIENT_ID,
    BIGCOMMERCE_CHANNEL_ID: process.env.BIGCOMMERCE_CHANNEL_ID,
    BIGCOMMERCE_STORE_URL: process.env.BIGCOMMERCE_STORE_URL,
    BIGCOMMERCE_STORE_API_CLIENT_SECRET: process.env.BIGCOMMERCE_STORE_API_CLIENT_SECRET,
    BIGCOMMERCE_STORE_API_STORE_HASH: process.env.BIGCOMMERCE_STORE_API_STORE_HASH,
    AIRTABLE_BASE_ID: process.env.AIRTABLE_BASE_ID,
    AIRTABLE_PERSONAL_ACCESS_TOKEN: process.env.AIRTABLE_PERSONAL_ACCESS_TOKEN,
    AIRTABLE_API_KEY: process.env.AIRTABLE_API_KEY,
  },
  images: {
    domains: ['cdn11.bigcommerce.com'],
  },
}
