import { Layout } from '@components/common'
import { Container, Text } from '@components/ui'
import { getConfig } from '@lib/data-hooks/api'
import getAllPages from '@lib/data-hooks/api/operations/get-all-pages'
import getSiteInfo from '@lib/data-hooks/api/operations/get-site-info'
import type { GetStaticPropsContext } from 'next'

export async function getStaticProps({
  preview,
  locale,
  locales,
}: GetStaticPropsContext) {
  const config = getConfig({ locale })
  const pagesPromise = getAllPages({ config, preview })
  const siteInfoPromise = getSiteInfo({ config, preview })
  const { pages } = await pagesPromise
  const { categories } = await siteInfoPromise

  return {
    props: { pages, categories },
  }
}

export default function Privacy() {
  return (
    <Container className="pt-16 pb-8">
      <Text variant="pageHeading">Privacy Policy</Text>
      {/* <h2 className="pt-6 text-xl font-bold tracking-wide">Privacy Policy</h2> */}
      <br />
      <p style={{ textAlign: 'justify', lineHeight: '1.6' }}>
        This Privacy Policy describes Our policies and procedures on the
        collection, use and disclosure of Your information when You use the
        Service and tells You about Your privacy rights and how the law protects
        You.
        <br />
        <br />
        We use Your Personal data to provide and improve the Service. By using
        the Service, You agree to the collection and use of information in
        accordance with this Privacy Policy. This Privacy Policy has been
        created with the help of the Privacy Policy Generator.
        <br />
        <br />
        <strong>
          {' '}
          <u>Interpretation and Definitions:</u>
        </strong>
        <br />
        <br />
        The words of which the initial letter is capitalized have meanings
        defined under the following conditions. The following definitions shall
        have the same meaning regardless of whether they appear in singular or
        in plural.
        <br />
        <br />
        <strong>Account: </strong> means a unique account created for You to
        access our Service or parts of our Service.
        <br />
        <br />
        <strong>Affiliate: </strong> means an entity that controls, is
        controlled by or is under common control with a party, where "control"
        means ownership of 50% or more of the shares, equity interest or other
        securities entitled to vote for election of directors or other managing
        authority.
        <br />
        <br />
        <strong>Company: </strong>(referred to as either "the Company", "We",
        "Us" or "Our" in this Agreement) refers to POOCHIE LLC, 5940 S Rainbow
        Blvd Ste 400 Las Vegas, Nevada.
        <br />
        <br />
        <strong>Cookies: </strong> are small files that are placed on Your
        computer, mobile device or any other device by a website, containing the
        details of Your browsing history on that website among its many uses.
        <br />
        <br />
        <strong>Country: </strong> refers to: California, United States
        <br />
        <br />
        <strong>Device: </strong>means any device that can access the Service
        such as a computer, a cellphone or a digital tablet.
        <br />
        <br />
        <strong>Personal Data: </strong>is any information that relates to an
        identified or identifiable individual.
        <br />
        <br />
        <strong>Service: </strong> refers to the Website.
        <br />
        <br />
        <h1>
          <u>
            <strong> Privacy Policy: </strong>
          </u>
          <br />
        </h1>
        <p style={{ textAlign: 'justify', lineHeight: '1.6' }}></p>
        <strong>Service Provider</strong> means any natural or legal person who
        processes the data on behalf of the Service Provider means any natural
        or legal person who processes the data on behalf of the Company. It
        refers to third-party companies or individuals employed by the Company
        to facilitate the Service, to provide the Service on behalf of the
        Company, to perform services related to the Service or to assist the
        Company in analyzing how the Service is used. Usage Data refers to data
        collected automatically, either generated by the use of the Service or
        from the Service infrastructure itself (for example, the duration of a
        page visit). Website refers to POOCHIE, accessible from
        https://www.poochie.co You means the individual accessing or using the
        Service, or the company, or other legal entity on behalf of which such
        individual is accessing or using the Service, as applicable. Collecting
        and Using Your Personal Data Types of Data Collected Personal Data While
        using Our Service, We may ask You to provide Us with certain personally
        identifiable information that can be used to contact or identify You.
        Personally identifiable information may include, but is not limited to:
        Email address First name and last name Usage Data Usage Data Usage Data
        is collected automatically when using the Service. Usage Data may
        include information such as Your Device's Internet Protocol address
        (e.g. IP address), browser type, browser version, the pages of our
        Service that You visit, the time and date of Your visit, the time spent
        on those pages, unique device identifiers and other diagnostic data.
        When You access the Service by or through a mobile device, We may
        collect certain information automatically, including, but not limited
        to, the type of mobile device You use, Your mobile device unique ID, the
        IP address of Your mobile device, Your mobile operating system, the type
        of mobile Internet browser You use, unique device identifiers and other
        diagnostic data. We may also collect information that Your browser sends
        whenever You visit our Service or when You access the Service by or
        through a mobile device.
      </p>

      <p style={{ textAlign: 'justify', lineHeight: '1.6' }}>
        Tracking Technologies and Cookies We use Cookies and similar tracking
        technologies to track the activity on Our Service and store certain
        information. Tracking technologies used are beacons, tags, and scripts
        to collect and track information and to improve and analyze Our Service.
        The technologies We use may include: Cookies or Browser Cookies. A
        cookie is a small file placed on Your Device. You can instruct Your
        browser to refuse all Cookies or to indicate when a Cookie is being
        sent. However, if You do not accept Cookies, You may not be able to use
        some parts of our Service. Unless you have adjusted Your browser setting
        so that it will refuse Cookies, our Service may use Cookies. Web
        Beacons. Certain sections of our Service and our emails may contain
        small electronic files known as web beacons (also referred to as clear
        gifs, pixel tags, and single-pixel gifs) that permit the Company, for
        example, to count users who have visited those pages or opened an email
        and for other related website statistics (for example, recording the
        popularity of a certain section and verifying system and server
        integrity). Cookies can be "Persistent" or "Session" Cookies. Persistent
        Cookies remain on Your personal computer or mobile device when You go
        offline, while Session Cookies are deleted as soon as You close Your web
        browser. Learn more about cookies on the Privacy Policies website
        article. We use both Session and Persistent Cookies for the purposes set
        out below: Necessary / Essential Cookies Type: Session Cookies
        Administered by: Us Purpose: These Cookies are essential to provide You
        with services available through the Website and to enable You to use
        some of its features. They help to authenticate users and prevent
        fraudulent use of user accounts. Without these Cookies, the services
        that You have asked for cannot be provided, and We only use these
        Cookies to provide You with those services. Cookies Policy / Notice
        Acceptance Cookies Type: Persistent Cookies Administered by: Us Purpose:
        These Cookies identify if users have accepted the use of cookies on the
        Website. Functionality Cookies Type: Persistent Cookies Administered by:
        Us Purpose: These Cookies allow us to remember choices You make when You
        use the Website, such as remembering your login details or language
        preference. The purpose of these Cookies is to provide You with a more
        personal experience and to avoid You having to re-enter your preferences
        every time You use the Website. For more information about the cookies
        we use and your choices regarding cookies, please visit our Cookies
        Policy or the Cookies section of our Privacy Policy.
      </p>
      <b />
      <b />
      <p>
        <strong>Affiliates</strong> include Our parent company and any other
        subsidiaries, joint venture partners or other companies that We control
        or that are under common control with Us.{' '}
        <strong>With business partners:</strong> We may share Your information
        with Our business partners to offer You certain products, services or
        promotions. <strong>With other users:</strong> when You share personal
        information or otherwise interact in the public areas with other users,
        such information may be viewed by all users and may be publicly
        distributed outside. <strong>With Your consent:</strong> We may disclose
        Your personal information for any other purpose with Your consent.{' '}
        <strong>Retention of Your Personal Data</strong> The Company will retain
        Your Personal Data only for as long as is necessary for the purposes set
        out in this Privacy Policy. We will retain and use Your Personal Data to
        the extent necessary to comply with our legal obligations (for example,
        if we are required to retain your data to comply with applicable laws),
        resolve disputes, and enforce our legal agreements and policies. The
        Company will also retain Usage Data for internal analysis purposes.
        Usage Data is generally retained for a shorter period of time, except
        when this data is used to strengthen the security or to improve the
        functionality of Our Service, or We are legally obligated to retain this
        data for longer time periods.{' '}
        <strong>Transfer of Your Personal Data</strong> Your information,
        including Personal Data, is processed at the Company's operating offices
        and in any other places where the parties involved in the processing are
        located. It means that this information may be transferred to — and
        maintained on — computers located outside of Your state, province,
        country or other governmental jurisdiction where the data protection
        laws may differ than those from Your jurisdiction. Your consent to this
        Privacy Policy followed by Your submission of such information
        represents Your agreement to that transfer. The Company will take all
        steps reasonably necessary to ensure that Your data is treated securely
        and in accordance with this Privacy Policy and no transfer of Your
        Personal Data will take place to an organization or a country unless
        there are adequate controls in place including the security of Your data
        and other personal information.{' '}
        <strong>Delete Your Personal Data</strong> You have the right to delete
        or request that We assist in deleting the Personal Data that We have
        collected about You. Our Service may give You the ability to delete
        certain information about You from within the Service. You may update,
        amend, or delete Your information at any time by signing in to Your
        Account, if you have one, and visiting the account settings section that
        allows you to manage Your personal information. You may also contact Us
        to request access to, correct, or delete any personal information that
        You have provided to Us. Please note, however, that We may need to
        retain certain information when we have a legal obligation or lawful
        basis to do so. <b /> <strong>Disclosure of Your Personal Data</strong>{' '}
        <em>Business Transactions</em> If the Company is involved in a merger,
        acquisition or asset sale, Your Personal Data may be transferred. We
        will provide notice before Your Personal Data is transferred and becomes
        subject to a different Privacy Policy. <em>Law enforcement</em> Under
        certain circumstances, the Company may be required to disclose Your
        Personal Data if required to do so by law or in response to valid
        requests by public authorities (e.g. a court or a government agency).{' '}
        <em>Other legal requirements</em> The Company may disclose Your Personal
        Data in the good faith belief that such action is necessary to: Comply
        with a legal obligation, Protect and defend the rights or property of
        the Company, Prevent or investigate possible wrongdoing in connection
        with the Service, Protect the personal safety of Users of the Service or
        the public, Protect against legal liability. <br />
        <br />
        <p>
          The security of your Personal Data is important to us; however, please
          remember that no method of transmission over the Internet or method of
          electronic storage is 100% secure. While we strive to use commercially
          acceptable means to protect your Personal Data, we cannot guarantee
          its absolute security.
        </p>
        <br />
        <h3>
          <b>
            <u>Children's Privacy: </u>
          </b>
        </h3>
        <p>
          Our Service does not address anyone under the age of 13. We do not
          knowingly collect personally identifiable information from anyone
          under the age of 13. If you are a parent or guardian and you are aware
          that your child has provided us with Personal Data, please contact us.
          If we become aware that we have collected Personal Data from anyone
          under the age of 13 without verification of parental consent, we take
          steps to remove that information from our servers.
        </p>
        <p>
          If we need to rely on consent as a legal basis for processing your
          information and your country requires consent from a parent, we may
          require your parent's consent before we collect and use that
          information.
        </p>
        <h3>Links to Other Websites</h3>
        <p>
          Our Service may contain links to other websites that are not operated
          by us. If you click on a third party link, you will be directed to
          that third party's site. We strongly advise you to review the Privacy
          Policy of every site you visit.
        </p>
        <p>
          We have no control over and assume no responsibility for the content,
          privacy policies, or practices of any third party sites or services.
        </p>
        <h3>Changes to this Privacy Policy</h3>
        <p>
          We may update our Privacy Policy from time to time. We will notify you
          of any changes by posting the new Privacy Policy on this page. We will
          let you know via email and/or a prominent notice on our Service, prior
          to the change becoming effective and update the "Last updated" date at
          the top of this Privacy Policy.
        </p>
        <p>
          You are advised to review this Privacy Policy periodically for any
          changes. Changes to this Privacy Policy are effective when they are
          posted on this page.
        </p>
        <br />
        <h3>
          <b>
            <u>Contact Us: </u>
          </b>
        </h3>
        <p>
          If you have any questions about this Privacy Policy, you can contact
          us: <i>shop@poochi.co</i>
        </p>
      </p>
    </Container>
  )
}

Privacy.Layout = Layout
